import { AudioManager } from "@/game/manager/AudioManager";
import {
    AnteScore,
    BlindCardsType,
    Decks,
    HandTypes,
    IHandData,
    PlayingCard,
    sceneNames,
    Stakes,
} from "@/types";
import BigNumber from "bignumber.js";

export const scenesBGMMap: Record<sceneNames, () => void> = {
    [sceneNames.MainMenu]: () => {
        AudioManager.getInstance().playMusic("music1", {
            volume: 0.6,
            rate: 0.7,
            fadeIn: 3 * 1000,
            protected: true, // 受保护，场景切换时不会被清理
        });
    },
    [sceneNames.Boot]: () => {},
    [sceneNames.Game]: () => {
        // 检查 music1 是否已经在播放（从 MainMenu 切换过来）
        const existingMusic = AudioManager.getInstance().getMusic("music1");
        if (!existingMusic || !existingMusic.isPlaying) {
            // 如果没有播放，才开始播放
            AudioManager.getInstance().playMusic("music1", {
                volume: 0.6,
                rate: 0.7,
                fadeIn: 3 * 1000,
                protected: true,
            });
        }
    },
    [sceneNames.GameOver]: () => {},
    [sceneNames.Preloader]: () => {},
    [sceneNames.Splash]: () => {},
};

/**
 *   赌注分数数组 索引代表底注等级
 */
const anteScoreArr: AnteScore[] = [
    {
        [Stakes.WhiteStake]: new BigNumber("100"),
        [Stakes.GreenStake]: new BigNumber("100"),
        [Stakes.PurpleStake]: new BigNumber("100"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("300"),
        [Stakes.GreenStake]: new BigNumber("300"),
        [Stakes.PurpleStake]: new BigNumber("300"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("800"),
        [Stakes.GreenStake]: new BigNumber("900"),
        [Stakes.PurpleStake]: new BigNumber("1000"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("2000"),
        [Stakes.GreenStake]: new BigNumber("2600"),
        [Stakes.PurpleStake]: new BigNumber("3200"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("5000"),
        [Stakes.GreenStake]: new BigNumber("8000"),
        [Stakes.PurpleStake]: new BigNumber("9000"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("11000"),
        [Stakes.GreenStake]: new BigNumber("20000"),
        [Stakes.PurpleStake]: new BigNumber("25000"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("20000"),
        [Stakes.GreenStake]: new BigNumber("36000"),
        [Stakes.PurpleStake]: new BigNumber("60000"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("35000"),
        [Stakes.GreenStake]: new BigNumber("60000"),
        [Stakes.PurpleStake]: new BigNumber("110000"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("50000"),
        [Stakes.GreenStake]: new BigNumber("100000"),
        [Stakes.PurpleStake]: new BigNumber("200000"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("110000"),
        [Stakes.GreenStake]: new BigNumber("200000"),
        [Stakes.PurpleStake]: new BigNumber("410000"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("560000"),
        [Stakes.GreenStake]: new BigNumber("1000000"),
        [Stakes.PurpleStake]: new BigNumber("2000000"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("7200000"),
        [Stakes.GreenStake]: new BigNumber("13000000"),
        [Stakes.PurpleStake]: new BigNumber("26000000"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("300000000"),
        [Stakes.GreenStake]: new BigNumber("540000000"),
        [Stakes.PurpleStake]: new BigNumber("1000000000"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("47000000000"),
        [Stakes.GreenStake]: new BigNumber("84000000000"),
        [Stakes.PurpleStake]: new BigNumber("1.60E+11"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("2.90E+13"),
        [Stakes.GreenStake]: new BigNumber("5.30E+13"),
        [Stakes.PurpleStake]: new BigNumber("1.00E+14"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("7.70E+16"),
        [Stakes.GreenStake]: new BigNumber("1.30E+17"),
        [Stakes.PurpleStake]: new BigNumber("2.70E+17"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("8.60E+20"),
        [Stakes.GreenStake]: new BigNumber("1.50E+21"),
        [Stakes.PurpleStake]: new BigNumber("3.10E+21"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("4.20E+25"),
        [Stakes.GreenStake]: new BigNumber("7.60E+25"),
        [Stakes.PurpleStake]: new BigNumber("1.50E+26"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("9.20E+30"),
        [Stakes.GreenStake]: new BigNumber("1.50E+31"),
        [Stakes.PurpleStake]: new BigNumber("3.30E+31"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("9.20E+36"),
        [Stakes.GreenStake]: new BigNumber("1.60E+37"),
        [Stakes.PurpleStake]: new BigNumber("3.30E+37"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("4.30E+43"),
        [Stakes.GreenStake]: new BigNumber("7.70E+43"),
        [Stakes.PurpleStake]: new BigNumber("1.50E+44"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("9.70E+50"),
        [Stakes.GreenStake]: new BigNumber("1.70E+51"),
        [Stakes.PurpleStake]: new BigNumber("3.40E+51"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("1.00E+59"),
        [Stakes.GreenStake]: new BigNumber("1.90E+59"),
        [Stakes.PurpleStake]: new BigNumber("3.80E+59"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("5.60E+67"),
        [Stakes.GreenStake]: new BigNumber("1.00E+68"),
        [Stakes.PurpleStake]: new BigNumber("2.10E+68"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("1.60E+77"),
        [Stakes.GreenStake]: new BigNumber("2.90E+77"),
        [Stakes.PurpleStake]: new BigNumber("5.90E+77"),
    },
    {
        [Stakes.WhiteStake]: new BigNumber("2.40E+87"),
        [Stakes.GreenStake]: new BigNumber("4.40E+87"),
        [Stakes.PurpleStake]: new BigNumber("8.80E+87"),
    },
];

export const blindCardsBtnTextMap = {
    [BlindCardsType.Active]: "选择",
    [BlindCardsType.Next]: "下一回合",
    [BlindCardsType.Pass]: "已被击败",
    [BlindCardsType.Skip]: "跳过",
};

export const HandsData: Record<HandTypes, IHandData> = {
    [HandTypes.FlushFive]: {
        desc: "5张相同点数和相同花色的牌",
        visible: false,
        order: 1,
        mult: 16,
        chips: 160,
        s_mult: 16,
        s_chips: 160,
        level: 1,
        l_mult: 3,
        l_chips: 50,
        played: 0,
        played_this_round: 0,
        example: [
            ["S_A", true],
            ["S_A", true],
            ["S_A", true],
            ["S_A", true],
            ["S_A", true],
        ],
    },
    [HandTypes.FlushHouse]: {
        desc: "三条及对子，且花色相同",
        visible: false,
        order: 2,
        mult: 14,
        chips: 140,
        s_mult: 14,
        s_chips: 140,
        level: 1,
        l_mult: 4,
        l_chips: 40,
        played: 0,
        played_this_round: 0,
        example: [
            ["D_7", true],
            ["D_7", true],
            ["D_7", true],
            ["D_4", true],
            ["D_4", true],
        ],
    },
    [HandTypes.FiveOfAKind]: {
        desc: "5张相同点数的牌",
        visible: false,
        order: 3,
        mult: 12,
        chips: 120,
        s_mult: 12,
        s_chips: 120,
        level: 1,
        l_mult: 3,
        l_chips: 35,
        played: 0,
        played_this_round: 0,
        example: [
            ["S_A", true],
            ["H_A", true],
            ["H_A", true],
            ["C_A", true],
            ["D_A", true],
        ],
    },
    [HandTypes.RoyalFlush]: {
        desc: "连续5张牌（点数连续），且花色相同",
        visible: true,
        order: 4,
        mult: 8,
        chips: 100,
        s_mult: 8,
        s_chips: 100,
        level: 1,
        l_mult: 4,
        l_chips: 40,
        played: 0,
        played_this_round: 0,
        example: [
            ["S_Q", true],
            ["S_J", true],
            ["S_T", true],
            ["S_9", true],
            ["S_8", true],
        ],
    },
    [HandTypes.StraightFlush]: {
        desc: "连续5张牌（点数连续），且花色相同",
        visible: true,
        order: 4,
        mult: 8,
        chips: 100,
        s_mult: 8,
        s_chips: 100,
        level: 1,
        l_mult: 4,
        l_chips: 40,
        played: 0,
        played_this_round: 0,
        example: [
            ["S_Q", true],
            ["S_J", true],
            ["S_T", true],
            ["S_9", true],
            ["S_8", true],
        ],
    },
    [HandTypes.FourOfAKind]: {
        desc: "4张相同点数的牌，可以与另外一张不计分的牌一同打出",
        visible: true,
        order: 5,
        mult: 7,
        chips: 60,
        s_mult: 7,
        s_chips: 60,
        level: 1,
        l_mult: 3,
        l_chips: 30,
        played: 0,
        played_this_round: 0,
        example: [
            ["S_J", true],
            ["H_J", true],
            ["C_J", true],
            ["D_J", true],
            ["C_3", false],
        ],
    },
    [HandTypes.FullHouse]: {
        desc: "三条及对子",
        visible: true,
        order: 6,
        mult: 4,
        chips: 40,
        s_mult: 4,
        s_chips: 40,
        level: 1,
        l_mult: 2,
        l_chips: 25,
        played: 0,
        played_this_round: 0,
        example: [
            ["H_K", true],
            ["C_K", true],
            ["D_K", true],
            ["S_2", true],
            ["D_2", true],
        ],
    },
    [HandTypes.Flush]: {
        desc: "5张牌花色相同",
        visible: true,
        order: 7,
        mult: 4,
        chips: 35,
        s_mult: 4,
        s_chips: 35,
        level: 1,
        l_mult: 2,
        l_chips: 15,
        played: 0,
        played_this_round: 0,
        example: [
            ["H_A", true],
            ["H_K", true],
            ["H_T", true],
            ["H_5", true],
            ["H_4", true],
        ],
    },
    [HandTypes.Straight]: {
        desc: "连续5张牌（点数连续）",
        visible: true,
        order: 8,
        mult: 4,
        chips: 30,
        s_mult: 4,
        s_chips: 30,
        level: 1,
        l_mult: 3,
        l_chips: 30,
        played: 0,
        played_this_round: 0,
        example: [
            ["D_J", true],
            ["C_T", true],
            ["C_9", true],
            ["S_8", true],
            ["H_7", true],
        ],
    },
    [HandTypes.ThreeOfAKind]: {
        desc: "3张点数相同的牌，可以与另外最多2张不计分的牌一同打出",
        visible: true,
        order: 9,
        mult: 3,
        chips: 30,
        s_mult: 3,
        s_chips: 30,
        level: 1,
        l_mult: 2,
        l_chips: 20,
        played: 0,
        played_this_round: 0,
        example: [
            ["S_T", true],
            ["C_T", true],
            ["D_T", true],
            ["H_6", false],
            ["D_5", false],
        ],
    },
    [HandTypes.TwoPair]: {
        desc: "两对不同点数的牌，可以与另外一张不计分的牌一同打出",
        visible: true,
        order: 10,
        mult: 2,
        chips: 20,
        s_mult: 2,
        s_chips: 20,
        level: 1,
        l_mult: 1,
        l_chips: 20,
        played: 0,
        played_this_round: 0,
        example: [
            ["H_A", true],
            ["D_A", true],
            ["C_Q", false],
            ["H_4", true],
            ["C_4", true],
        ],
    },
    [HandTypes.Pair]: {
        desc: "两张点数相同的牌，可以与另外最多3张不计分的牌一同打出",
        visible: true,
        order: 11,
        mult: 2,
        chips: 10,
        s_mult: 2,
        s_chips: 10,
        level: 1,
        l_mult: 1,
        l_chips: 15,
        played: 0,
        played_this_round: 0,
        example: [
            ["S_K", false],
            ["S_9", true],
            ["D_9", true],
            ["H_6", false],
            ["D_3", false],
        ],
    },
    [HandTypes.HighCard]: {
        desc: "如果打出的牌不是以上任何一种那么只有点数最高的牌会计分",
        visible: true,
        order: 12,
        mult: 1,
        chips: 5,
        s_mult: 1,
        s_chips: 5,
        level: 1,
        l_mult: 1,
        l_chips: 10,
        played: 0,
        played_this_round: 0,
        example: [
            ["S_A", true],
            ["D_Q", false],
            ["D_9", false],
            ["C_4", false],
            ["D_3", false],
        ],
    },
};
