import { AudioManager } from "@/game/manager/AudioManager";
import {
    BlindCardTypes,
    HandTypes,
    sceneNames,
    StakeNames,
    Suits,
    PlayingCardValues,
    HandDataValue,
    BlindNames,
    BlindDefinition,
    StakeDefinition,
} from "@/types";

/** 场景背景音乐映射 */
export const scenesBGMMap: Readonly<Record<sceneNames, () => void>> = {
    [sceneNames.MainMenu]: () => {
        AudioManager.getInstance().playMusic("music1", {
            volume: 0.6,
            rate: 0.7,
            fadeIn: 3 * 1000,
            protected: true, // 受保护，场景切换时不会被清理
        });
    },
    [sceneNames.Boot]: () => {},
    [sceneNames.Game]: () => {
        // 检查 music1 是否已经在播放（从 MainMenu 切换过来）
        const existingMusic = AudioManager.getInstance().getMusic("music1");
        if (!existingMusic || !existingMusic.isPlaying) {
            // 如果没有播放，才开始播放
            AudioManager.getInstance().playMusic("music1", {
                volume: 0.6,
                rate: 0.7,
                fadeIn: 3 * 1000,
                protected: true,
            });
        }
    },
    [sceneNames.GameOver]: () => {},
    [sceneNames.Preloader]: () => {},
    [sceneNames.Splash]: () => {},
};

/** 盲注按钮文本映射 */
export const blindCardsBtnTextMap: Readonly<Record<BlindCardTypes, string>> = {
    [BlindCardTypes.Active]: "选择",
    [BlindCardTypes.Next]: "下一回合",
    [BlindCardTypes.Pass]: "已被击败",
    [BlindCardTypes.Skip]: "跳过",
};

/** 牌型数据 */
export const HandsDataMap: Readonly<Record<HandTypes, HandDataValue>> = {
    [HandTypes.FlushFive]: {
        desc: "5张相同点数和相同花色的牌",
        visible: false,
        order: 1,
        mult: 16,
        chips: 160,
        s_mult: 16,
        s_chips: 160,
        level: 1,
        l_mult: 3,
        l_chips: 50,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
        ],
    },
    [HandTypes.FlushHouse]: {
        desc: "三条及对子，且花色相同",
        visible: false,
        order: 2,
        mult: 14,
        chips: 140,
        s_mult: 14,
        s_chips: 140,
        level: 1,
        l_mult: 4,
        l_chips: 40,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.Seven} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Seven,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Seven} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Seven,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Seven} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Seven,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Four} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Four,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Four} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Four,
                isScoring: true,
            },
        ],
    },
    [HandTypes.FiveOfAKind]: {
        desc: "5张相同点数的牌",
        visible: false,
        order: 3,
        mult: 12,
        chips: 120,
        s_mult: 12,
        s_chips: 120,
        level: 1,
        l_mult: 3,
        l_chips: 35,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
        ],
    },
    [HandTypes.RoyalFlush]: {
        desc: "连续5张牌（点数连续），且花色相同",
        visible: true,
        order: 4,
        mult: 8,
        chips: 100,
        s_mult: 8,
        s_chips: 100,
        level: 1,
        l_mult: 4,
        l_chips: 40,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.King} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.King,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Queen} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Queen,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Jack} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Jack,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ten} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Ten,
                isScoring: true,
            },
        ],
    },
    [HandTypes.StraightFlush]: {
        desc: "连续5张牌（点数连续），且花色相同",
        visible: true,
        order: 4,
        mult: 8,
        chips: 100,
        s_mult: 8,
        s_chips: 100,
        level: 1,
        l_mult: 4,
        l_chips: 40,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.Queen} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Queen,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Jack} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Jack,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ten} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Ten,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Nine} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Nine,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Eight} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Eight,
                isScoring: true,
            },
        ],
    },
    [HandTypes.FourOfAKind]: {
        desc: "4张相同点数的牌，可以与另外一张不计分的牌一同打出",
        visible: true,
        order: 5,
        mult: 7,
        chips: 60,
        s_mult: 7,
        s_chips: 60,
        level: 1,
        l_mult: 3,
        l_chips: 30,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.Jack} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Jack,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Jack} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.Jack,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Jack} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Jack,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Jack} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Jack,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Three} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Three,
                isScoring: false,
            },
        ],
    },
    [HandTypes.FullHouse]: {
        desc: "三条及对子",
        visible: true,
        order: 6,
        mult: 4,
        chips: 40,
        s_mult: 4,
        s_chips: 40,
        level: 1,
        l_mult: 2,
        l_chips: 25,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.King} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.King,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.King} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.King,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.King} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.King,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Two} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Two,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Two} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Two,
                isScoring: true,
            },
        ],
    },
    [HandTypes.Flush]: {
        desc: "5张牌花色相同",
        visible: true,
        order: 7,
        mult: 4,
        chips: 35,
        s_mult: 4,
        s_chips: 35,
        level: 1,
        l_mult: 2,
        l_chips: 15,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.King} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.King,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ten} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.Ten,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Five} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.Five,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Four} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.Four,
                isScoring: true,
            },
        ],
    },
    [HandTypes.Straight]: {
        desc: "连续5张牌（点数连续）",
        visible: true,
        order: 8,
        mult: 4,
        chips: 30,
        s_mult: 4,
        s_chips: 30,
        level: 1,
        l_mult: 3,
        l_chips: 30,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.Jack} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Jack,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ten} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Ten,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Nine} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Nine,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Eight} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Eight,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Seven} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.Seven,
                isScoring: true,
            },
        ],
    },
    [HandTypes.ThreeOfAKind]: {
        desc: "3张点数相同的牌，可以与另外最多2张不计分的牌一同打出",
        visible: true,
        order: 9,
        mult: 3,
        chips: 30,
        s_mult: 3,
        s_chips: 30,
        level: 1,
        l_mult: 2,
        l_chips: 20,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.Ten} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Ten,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ten} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Ten,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ten} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Ten,
                isScoring: true,
            },

            {
                name: `${PlayingCardValues.Six} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.Six,
                isScoring: false,
            },
            {
                name: `${PlayingCardValues.Five} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Five,
                isScoring: false,
            },
        ],
    },
    [HandTypes.TwoPair]: {
        desc: "两对不同点数的牌，可以与另外一张不计分的牌一同打出",
        visible: true,
        order: 10,
        mult: 2,
        chips: 20,
        s_mult: 2,
        s_chips: 20,
        level: 1,
        l_mult: 1,
        l_chips: 20,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Queen} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Queen,
                isScoring: false,
            },
            {
                name: `${PlayingCardValues.Four} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.Four,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Four} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Four,
                isScoring: true,
            },
        ],
    },
    [HandTypes.Pair]: {
        desc: "两张点数相同的牌，可以与另外最多3张不计分的牌一同打出",
        visible: true,
        order: 11,
        mult: 2,
        chips: 10,
        s_mult: 2,
        s_chips: 10,
        level: 1,
        l_mult: 1,
        l_chips: 15,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.King} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.King,
                isScoring: false,
            },
            {
                name: `${PlayingCardValues.Nine} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Nine,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Nine} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Nine,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Six} of ${Suits.Hearts}`,
                suit: Suits.Hearts,
                value: PlayingCardValues.Six,
                isScoring: false,
            },
            {
                name: `${PlayingCardValues.Three} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Three,
                isScoring: false,
            },
        ],
    },
    [HandTypes.HighCard]: {
        desc: "如果打出的牌不是以上任何一种那么只有点数最高的牌会计分",
        visible: true,
        order: 12,
        mult: 1,
        chips: 5,
        s_mult: 1,
        s_chips: 5,
        level: 1,
        l_mult: 1,
        l_chips: 10,
        played: 0,
        played_this_round: 0,
        example: [
            {
                name: `${PlayingCardValues.Ace} of ${Suits.Spades}`,
                suit: Suits.Spades,
                value: PlayingCardValues.Ace,
                isScoring: true,
            },
            {
                name: `${PlayingCardValues.Queen} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Queen,
                isScoring: false,
            },
            {
                name: `${PlayingCardValues.Nine} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Nine,
                isScoring: false,
            },
            {
                name: `${PlayingCardValues.Four} of ${Suits.Clubs}`,
                suit: Suits.Clubs,
                value: PlayingCardValues.Four,
                isScoring: false,
            },
            {
                name: `${PlayingCardValues.Three} of ${Suits.Diamonds}`,
                suit: Suits.Diamonds,
                value: PlayingCardValues.Three,
                isScoring: false,
            },
        ],
    },
};

/** 盲注数据映射 */
export const BlindsDataMap: Readonly<Record<BlindNames, BlindDefinition>> = {
    [BlindNames.SmallBlind]: {
        name: "小盲注",
        defeated: false,
        order: 1,
        dollars: 3,
        mult: 1,
        vars: [],
        debuff_text: "",
        debuff: {},
        pos: { x: 0, y: 0 },
    },
    [BlindNames.BigBlind]: {
        name: "大盲注",
        defeated: false,
        order: 2,
        dollars: 4,
        mult: 1.5,
        vars: [],
        debuff_text: "",
        debuff: {},
        pos: { x: 0, y: 1 },
    },
    [BlindNames.TheHook]: {
        name: "钩子",
        defeated: false,
        order: 3,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 7 },
        boss: { min: 1, max: 10 },
        boss_colour: "#a84024",
    },
    [BlindNames.TheOx]: {
        name: "公牛",
        defeated: false,
        order: 4,
        dollars: 5,
        mult: 2,
        vars: ["localize:ph_most_played"],
        debuff: {},
        pos: { x: 0, y: 2 },
        boss: { min: 6, max: 10 },
        boss_colour: "#b95b08",
    },
    [BlindNames.TheHouse]: {
        name: "房屋",
        defeated: false,
        order: 5,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 3 },
        boss: { min: 2, max: 10 },
        boss_colour: "#5186a8",
    },
    [BlindNames.TheWall]: {
        name: "围墙",
        defeated: false,
        order: 6,
        dollars: 5,
        mult: 4,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 9 },
        boss: { min: 2, max: 10 },
        boss_colour: "#8a59a5",
    },
    [BlindNames.TheWheel]: {
        name: "车轮",
        defeated: false,
        order: 7,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 10 },
        boss: { min: 2, max: 10 },
        boss_colour: "#50bf7c",
    },
    [BlindNames.TheArm]: {
        name: "手臂",
        defeated: false,
        order: 8,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 11 },
        boss: { min: 2, max: 10 },
        boss_colour: "#6865f3",
    },
    [BlindNames.TheClub]: {
        name: "梅花",
        defeated: false,
        order: 9,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: { suit: Suits.Clubs },
        pos: { x: 0, y: 4 },
        boss: { min: 1, max: 10 },
        boss_colour: "#b9cb92",
    },
    [BlindNames.TheFish]: {
        name: "鱼",
        defeated: false,
        order: 10,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 5 },
        boss: { min: 2, max: 10 },
        boss_colour: "#3e85bd",
    },
    [BlindNames.ThePsychic]: {
        name: "灵媒",
        defeated: false,
        order: 11,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: { h_size_ge: 5 },
        pos: { x: 0, y: 12 },
        boss: { min: 1, max: 10 },
        boss_colour: "#efc03c",
    },
    [BlindNames.TheGoad]: {
        name: "挑衅",
        defeated: false,
        order: 12,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: { suit: Suits.Spades },
        pos: { x: 0, y: 13 },
        boss: { min: 1, max: 10 },
        boss_colour: "#b95c96",
    },
    [BlindNames.TheWater]: {
        name: "水",
        defeated: false,
        order: 13,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 14 },
        boss: { min: 2, max: 10 },
        boss_colour: "#c6e0eb",
    },
    [BlindNames.TheWindow]: {
        name: "窗口",
        defeated: false,
        order: 14,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: { suit: Suits.Diamonds },
        pos: { x: 0, y: 6 },
        boss: { min: 1, max: 10 },
        boss_colour: "#a9a295",
    },
    [BlindNames.TheManacle]: {
        name: "镣铐",
        defeated: false,
        order: 15,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 8 },
        boss: { min: 1, max: 10 },
        boss_colour: "#575757",
    },
    [BlindNames.TheEye]: {
        name: "眼睛",
        defeated: false,
        order: 16,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 17 },
        boss: { min: 3, max: 10 },
        boss_colour: "#4b71e4",
    },
    [BlindNames.TheMouth]: {
        name: "嘴巴",
        defeated: false,
        order: 17,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 18 },
        boss: { min: 2, max: 10 },
        boss_colour: "#ae718e",
    },
    [BlindNames.ThePlant]: {
        name: "植物",
        defeated: false,
        order: 18,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: { is_face: "face" },
        pos: { x: 0, y: 19 },
        boss: { min: 4, max: 10 },
        boss_colour: "#709284",
    },
    [BlindNames.TheSerpent]: {
        name: "巨蟒",
        defeated: false,
        order: 19,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 15 },
        boss: { min: 5, max: 10 },
        boss_colour: "#439a4f",
    },
    [BlindNames.ThePillar]: {
        name: "支柱",
        defeated: false,
        order: 20,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 16 },
        boss: { min: 1, max: 10 },
        boss_colour: "#7e6752",
    },
    [BlindNames.TheNeedle]: {
        name: "针",
        defeated: false,
        order: 21,
        dollars: 5,
        mult: 1,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 20 },
        boss: { min: 2, max: 10 },
        boss_colour: "#5c6e31",
    },
    [BlindNames.TheHead]: {
        name: "头部",
        defeated: false,
        order: 22,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: { suit: Suits.Hearts },
        pos: { x: 0, y: 21 },
        boss: { min: 1, max: 10 },
        boss_colour: "#ac9db4",
    },
    [BlindNames.TheTooth]: {
        name: "牙齿",
        defeated: false,
        order: 23,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 22 },
        boss: { min: 3, max: 10 },
        boss_colour: "#b52d2d",
    },
    [BlindNames.TheFlint]: {
        name: "燧石",
        defeated: false,
        order: 24,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 24 },
        boss: { min: 2, max: 10 },
        boss_colour: "#e56a2f",
    },
    [BlindNames.TheMark]: {
        name: "标记",
        defeated: false,
        order: 25,
        dollars: 5,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 23 },
        boss: { min: 2, max: 10 },
        boss_colour: "#6a3847",
    },
    [BlindNames.AmberAcorn]: {
        name: "琥珀之实",
        defeated: false,
        order: 26,
        dollars: 8,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 27 },
        boss: { showdown: true, min: 10, max: 10 },
        boss_colour: "#fda200",
    },
    [BlindNames.VerdantLeaf]: {
        name: "翠绿之叶",
        defeated: false,
        order: 27,
        dollars: 8,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 28 },
        boss: { showdown: true, min: 10, max: 10 },
        boss_colour: "#56a786",
    },
    [BlindNames.VioletVessel]: {
        name: "靛紫之杯",
        defeated: false,
        order: 28,
        dollars: 8,
        mult: 6,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 29 },
        boss: { showdown: true, min: 10, max: 10 },
        boss_colour: "#8a71e1",
    },
    [BlindNames.CrimsonHeart]: {
        name: "绯红之心",
        defeated: false,
        order: 29,
        dollars: 8,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 25 },
        boss: { showdown: true, min: 10, max: 10 },
        boss_colour: "#ac3232",
    },
    [BlindNames.CeruleanBell]: {
        name: "蔚蓝之铃",
        defeated: false,
        order: 30,
        dollars: 8,
        mult: 2,
        vars: [],
        debuff: {},
        pos: { x: 0, y: 26 },
        boss: { showdown: true, min: 10, max: 10 },
        boss_colour: "#009cfd",
    },
};

/** 赌注数据映射 */
export const stakeDataMap: Readonly<Record<StakeNames, StakeDefinition>> = {
    [StakeNames.WhiteStake]: {
        name: "White Chip",
        unlocked: true,
        order: 1,
        pos: {
            x: 0,
            y: 0,
        },
        stake_level: 1,
    },
    [StakeNames.RedStake]: {
        name: "Red Chip",
        unlocked: false,
        order: 2,
        pos: {
            x: 1,
            y: 0,
        },
        stake_level: 2,
    },
    [StakeNames.GreenStake]: {
        name: "Green Chip",
        unlocked: false,
        order: 3,
        pos: {
            x: 2,
            y: 0,
        },
        stake_level: 3,
    },
    [StakeNames.BlackStake]: {
        name: "Black Chip",
        unlocked: false,
        order: 4,
        pos: {
            x: 4,
            y: 0,
        },
        stake_level: 4,
    },
    [StakeNames.BlueStake]: {
        name: "Blue Chip",
        unlocked: false,
        order: 5,
        pos: {
            x: 3,
            y: 0,
        },
        stake_level: 5,
    },
    [StakeNames.PurpleStake]: {
        name: "Purple Chip",
        unlocked: false,
        order: 6,
        pos: {
            x: 0,
            y: 1,
        },
        stake_level: 6,
    },
    [StakeNames.OrangeStake]: {
        name: "Orange Chip",
        unlocked: false,
        order: 7,
        pos: {
            x: 1,
            y: 1,
        },
        stake_level: 7,
    },
    [StakeNames.GoldStake]: {
        name: "Gold Chip",
        unlocked: false,
        order: 8,
        pos: {
            x: 2,
            y: 1,
        },
        stake_level: 8,
    },
};
